data<-read.csv('marker.csv',quote='',header=T,row.names=1,check.names=F)
names(data)<-'symbol'
library(org.Hs.eg.db)
library(clusterProfiler)
symbol=toTable(org.Hs.egSYMBOL)
data<-merge(data,symbol,by='symbol')
ekk <- enrichKEGG(gene=data$gene_id,organism  = 'hsa',pvalueCutoff=0.1,qvalueCutoff=0.2)
pdf('kegg.pdf',height=8,width=7.5)
dotplot(ekk, showCategory = 20)
dev.off()

ego_bp<-enrichGO(OrgDb="org.Hs.eg.db",gene = data$gene_id, ont = "BP",readable=TRUE)
ego_cc<-enrichGO(OrgDb="org.Hs.eg.db",gene = data$gene_id, ont = "CC",readable=TRUE)
ego_mf<-enrichGO(OrgDb="org.Hs.eg.db",gene = data$gene_id, ont = "MF",readable=TRUE)
pdf('bp.pdf',height=8,width=8)
dotplot(ego_bp, showCategory = 20)
dev.off()
pdf('cc.pdf',height=8,width=6.6)
dotplot(ego_cc, showCategory = 20)
dev.off()
pdf('mf.pdf',height=8,width=7.5)
dotplot(ego_mf, showCategory = 20)
dev.off()
